-- comment added
USE WAREHOUSE COMPUTE_WH;
SELECT CURRENT_WAREHOUSE();

USE ROLE SYSADMIN;

SHOW DATABASES;
USE DATABASE DEMO;

--DROP SCHEMA FILE_INGESTION_DEMO;

CREATE OR REPLACE SCHEMA FILE_INGESTION_DEMO;
USE SCHEMA FILE_INGESTION_DEMO;

-- Create a bucket in AWS and upload files for the demo
-- Create an IAM Role in AWS with External Id and give S3 full access

USE ROLE ACCOUNTADMIN;
SHOW STORAGE INTEGRATIONS;
-- Create storage integration object to connect to S3
CREATE STORAGE INTEGRATION IF NOT EXISTS  S3_INT_JS_PS_DEMO
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::012345678900:role/jsuresh-ps-snowflake-access-role' -- Copy the AWS ARN from AWS IAM Role
STORAGE_ALLOWED_LOCATIONS = ('s3://jsuresh-ps-demo/raw-sample/'); -- file path or bucket details

DESC  INTEGRATION S3_INT_JS_PS_DEMO; -- Copy the STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID and paste in the S3 IAM Role - Trusted Relationships and update the policy
GRANT USAGE ON INTEGRATION S3_INT_JS_PS_DEMO TO ROLE SYSADMIN;
-- Now storage integration is ready for use




USE ROLE SYSADMIN;
USE SCHEMA FILE_INGESTION_DEMO;

-- ------------------------------------------------------------
-- Raw Layer Objects
--     1.  Create the destination tables - Orders and Customer
--     2.  3 tracking fields are being added to each table:
--         File_Name, Load_DateTime, Load_By
--     3.  Create the stage
--     4.  Create 2 file formats (CSV and JSON)
-- ------------------------------------------------------------





-- Create External Stage
CREATE OR REPLACE STAGE DEMO.FILE_INGESTION_DEMO.TPCH_STG
STORAGE_INTEGRATION = S3_INT_JS_PS_DEMO
URL = 's3://jsuresh-ps-demo/raw-sample/';

-- Upload file in S3 bucket and view it in the stage
LIST @DEMO.FILE_INGESTION_DEMO.TPCH_STG;

-- Create internal stage
CREATE OR REPLACE STAGE DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG;
LIST @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG; -- No files right now

--- File Format providing file definition
CREATE OR REPLACE FILE FORMAT DEMO.FILE_INGESTION_DEMO.TPCH_ORDERS_CSV 
    SKIP_HEADER = 1;

CREATE OR REPLACE FILE FORMAT DEMO.FILE_INGESTION_DEMO.TPCH_CUSTOMER_JSON
  TYPE = JSON
  COMPRESSION = NONE
;
--- Tables
CREATE OR REPLACE TABLE ORDERS (
    O_ORDERKEY              NUMBER,
    O_CUSTKEY               NUMBER, 
    O_ORDERSTATUS           STRING, 
    O_TOTALPRICE            NUMBER, 
    O_ORDERDATE             DATE, 
    O_ORDERPRIORITY         STRING, 
    O_CLERK                 STRING, 
    O_SHIPPRIORITY          NUMBER, 
    O_COMMENT               STRING, 
    FILE_NAME               STRING NOT NULL, 
    LOAD_DATETIME           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    LOAD_BY                 STRING NOT NULL DEFAULT CURRENT_USER()
);

CREATE OR REPLACE TABLE CUSTOMER (
    C_CUSTKEY NUMBER(38,0),
    CUSTOMER_RECORD VARIANT,
    FILE_NAME VARCHAR, 
    FILE_ROW_NUMBER VARCHAR,
    LOAD_DATETIME TIMESTAMP,
    LOAD_BY VARCHAR  
);
-- Add the rest of the TPCH tables with the 3 additional columns

/*create or replace TABLE LINEITEM (
	L_ORDERKEY NUMBER(38,0) NOT NULL,
	L_PARTKEY NUMBER(38,0) NOT NULL,
	L_SUPPKEY NUMBER(38,0) NOT NULL,
	L_LINENUMBER NUMBER(38,0) NOT NULL,
	L_QUANTITY NUMBER(12,2) NOT NULL,
	L_EXTENDEDPRICE NUMBER(12,2) NOT NULL,
	L_DISCOUNT NUMBER(12,2) NOT NULL,
	L_TAX NUMBER(12,2) NOT NULL,
	L_RETURNFLAG VARCHAR(1) NOT NULL,
	L_LINESTATUS VARCHAR(1) NOT NULL,
	L_SHIPDATE DATE NOT NULL,
	L_COMMITDATE DATE NOT NULL,
	L_RECEIPTDATE DATE NOT NULL,
	L_SHIPINSTRUCT VARCHAR(25) NOT NULL,
	L_SHIPMODE VARCHAR(10) NOT NULL,
	L_COMMENT VARCHAR(44) NOT NULL, 
    FILE_NAME               STRING NOT NULL, 
    LOAD_DATETIME           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    LOAD_BY                 STRING NOT NULL DEFAULT CURRENT_USER()
);

create or replace TABLE NATION (
	N_NATIONKEY NUMBER(38,0) NOT NULL,
	N_NAME VARCHAR(25) NOT NULL,
	N_REGIONKEY NUMBER(38,0) NOT NULL,
	N_COMMENT VARCHAR(152), 
    FILE_NAME               STRING NOT NULL, 
    LOAD_DATETIME           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    LOAD_BY                 STRING NOT NULL DEFAULT CURRENT_USER()
);

create or replace TABLE PART (
	P_PARTKEY NUMBER(38,0) NOT NULL,
	P_NAME VARCHAR(55) NOT NULL,
	P_MFGR VARCHAR(25) NOT NULL,
	P_BRAND VARCHAR(10) NOT NULL,
	P_TYPE VARCHAR(25) NOT NULL,
	P_SIZE NUMBER(38,0) NOT NULL,
	P_CONTAINER VARCHAR(10) NOT NULL,
	P_RETAILPRICE NUMBER(12,2) NOT NULL,
	P_COMMENT VARCHAR(23), 
    FILE_NAME               STRING NOT NULL, 
    LOAD_DATETIME           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    LOAD_BY                 STRING NOT NULL DEFAULT CURRENT_USER()
);

create or replace TABLE PARTSUPP (
	PS_PARTKEY NUMBER(38,0) NOT NULL,
	PS_SUPPKEY NUMBER(38,0) NOT NULL,
	PS_AVAILQTY NUMBER(38,0) NOT NULL,
	PS_SUPPLYCOST NUMBER(12,2) NOT NULL,
	PS_COMMENT VARCHAR(199), 
    FILE_NAME               STRING NOT NULL, 
    LOAD_DATETIME           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    LOAD_BY                 STRING NOT NULL DEFAULT CURRENT_USER()
);

create or replace TABLE REGION (
	R_REGIONKEY NUMBER(38,0) NOT NULL,
	R_NAME VARCHAR(25) NOT NULL,
	R_COMMENT VARCHAR(152), 
    FILE_NAME               STRING NOT NULL, 
    LOAD_DATETIME           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), 
    LOAD_BY                 STRING NOT NULL DEFAULT CURRENT_USER()
);
*/