
-- comment added
USE WAREHOUSE COMPUTE_WH;
SELECT CURRENT_WAREHOUSE();

USE ROLE SYSADMIN;
SELECT CURRENT_ROLE();
--SHOW DATABASES;
USE DATABASE DEMO;

USE SCHEMA FILE_INGESTION_DEMO;
SHOW STAGES;

 SELECT *
    FROM snowflake_sample_data.tpch_sf1.orders LIMIT 10;

COPY INTO @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/ORDERS/Orders
FROM (
--    SELECT 
--        O_ORDERKEY,O_CUSTKEY,O_ORDERSTATUS,O_TOTALPRICE,'2024-05-23' AS O_ORDERDATE,O_ORDERPRIORITY,O_CLERK,O_SHIPPRIORITY,O_COMMENT
--    FROM snowflake_sample_data.tpch_sf1.orders 
--    WHERE O_ORDERDATE = '1992-01-01'    
    SELECT *
    FROM snowflake_sample_data.tpch_sf1.orders 
  
)
HEADER=TRUE
OVERWRITE=TRUE
;

SELECT 
            to_JSON(OBJECT_CONSTRUCT(*)) -- creates a json record 
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER 
    LIMIT 100
;

COPY INTO  @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/CUSTOMER/customer
FROM (
    SELECT 
        OBJECT_CONSTRUCT(*)
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER 
) 
--INCLUDE_QUERY_ID=TRUE
OVERWRITE=TRUE
FILE_FORMAT = (FORMAT_NAME=DEMO.FILE_INGESTION_DEMO.TPCH_CUSTOMER_JSON)
;

-- View the files loaded in the internal stage
LIST @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/ORDERS;
LIST @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/CUSTOMER;

-- Take a look at our data 
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, metadata$filename,CURRENT_TIMESTAMP(),CURRENT_USER() 
from @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/ORDERS/ 
;

-- Customers data
/*SELECT $1  -- Full Json Field
    ,PARSE_JSON($1):C_CUSTKEY as customer_key
    , METADATA$FILENAME,METADATA$FILE_ROW_NUMBER,CURRENT_TIMESTAMP(),CURRENT_USER() 
from @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/CUSTOMER/ 
(file_format => DEMO.FILE_INGESTION_DEMO.TPCH_CUSTOMER_JSON);*/

-- Metadata Only options: 
SELECT METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_CONTENT_KEY, METADATA$FILE_LAST_MODIFIED, METADATA$START_SCAN_TIME,$1 
from @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/CUSTOMER/
(file_format => DEMO.FILE_INGESTION_DEMO.TPCH_CUSTOMER_JSON);



--TRUNCATE TABLE  DEMO.FILE_INGESTION_DEMO.ORDERS;
--TRUNCATE TABLE  DEMO.FILE_INGESTION_DEMO.CUSTOMER; 

SELECT * FROM DEMO.FILE_INGESTION_DEMO.ORDERS;
SELECT * FROM DEMO.FILE_INGESTION_DEMO.CUSTOMER;