USE WAREHOUSE COMPUTE_WH;
SELECT CURRENT_WAREHOUSE();

USE ROLE SYSADMIN;
SELECT CURRENT_ROLE();
--SHOW DATABASES;
USE DATABASE DEMO;

USE SCHEMA FILE_INGESTION_DEMO;
--- Copy Options

select COUNT(1) FROM DEMO.FILE_INGESTION_DEMO.CUSTOMER;

-- Run below COPY statements - this contains a FORCE=TRUE property to force a file already loaded
COPY INTO DEMO.FILE_INGESTION_DEMO.CUSTOMER
FROM (
    SELECT 
        PARSE_JSON($1):C_CUSTKEY,
        $1, 
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        CURRENT_TIMESTAMP(),
        CURRENT_USER()        
    FROM @DEMO.FILE_INGESTION_DEMO.TPCH_INT_STG/CUSTOMER
) 
FILE_FORMAT = DEMO.FILE_INGESTION_DEMO.TPCH_CUSTOMER_JSON
--FORCE=TRUE
ON_ERROR=CONTINUE
;

select count(*) from DEMO.FILE_INGESTION_DEMO.CUSTOMER; -- Record count should be doubled due to force load - 3000000

-- ------------------------------------------------------------
-- Error Handling / Troubleshooting / Monitoring
-- ------------------------------------------------------------

LIST @DEMO.FILE_INGESTION_DEMO.TPCH_STG;

SELECT $1, $2, $3 FROM @DEMO.FILE_INGESTION_DEMO.TPCH_STG;

CREATE OR REPLACE TABLE  DEMO.FILE_INGESTION_DEMO.EMPLOYEE
(
 EMPLOYEE_NAME              STRING,
    GENDER               STRING, 
    IS_EMPLOYED           BOOLEAN
);


TRUNCATE TABLE DEMO.FILE_INGESTION_DEMO.EMPLOYEE;

SELECT * FROM DEMO.FILE_INGESTION_DEMO.EMPLOYEE;


COPY INTO  DEMO.FILE_INGESTION_DEMO.EMPLOYEE
FROM @DEMO.FILE_INGESTION_DEMO.TPCH_STG
FILE_FORMAT = DEMO.FILE_INGESTION_DEMO.TPCH_ORDERS_CSV
--ON_ERROR = CONTINUE;
--ON_ERROR=SKIP_FILE;
--ON_ERROR =  ABORT_STATEMENT
--ON_ERROR = SKIP_FILE_2;
ON_ERROR = 'SKIP_FILE_80%';

SELECT * FROM DEMO.FILE_INGESTION_DEMO.EMPLOYEE;
