USE WAREHOUSE COMPUTE_WH;
SELECT CURRENT_WAREHOUSE();

USE ROLE SYSADMIN;
SELECT CURRENT_ROLE();
--SHOW DATABASES;
USE DATABASE DEMO;

USE SCHEMA FILE_INGESTION_DEMO;


-- ------------------------------------------------------------
-- Monitoring 
-- ------------------------------------------------------------
-- Copy Command History
SELECT 
    *
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME=>'DEMO.FILE_INGESTION_DEMO.EMPLOYEE',
    START_TIME=> DATEADD(DAY, -1, CURRENT_TIMESTAMP()))
)
ORDER BY LAST_LOAD_TIME DESC
LIMIT 100
;
-- Load History by Table
SELECT *
FROM INFORMATION_SCHEMA.LOAD_HISTORY
WHERE SCHEMA_NAME='FILE_INGESTION_DEMO' 
AND TABLE_NAME='EMPLOYEE'
ORDER BY LAST_LOAD_TIME DESC
LIMIT 100
;














-- Result Scan & Validate
--SET q_id = (SELECT LAST_QUERY_ID());

/*SELECT 
    $q_id AS QUERY_ID,
    --OBJECT_CONSTRUCT(*) AS RESULT_OBJECT    
    ARRAY_AGG(OBJECT_CONSTRUCT(*)) WITHIN GROUP (ORDER BY QUERY_ID)    
FROM TABLE(RESULT_SCAN($q_id))
;*


-- Below validate via job_id was not working.  included a different option below
--SELECT * FROM TABLE(VALIDATE(DEMO.FILE_INGESTION_DEMO.EMPLOYEE, JOB_ID=>'01c0cd7f-0004-0424-000a-60c60007b08e'));
-- SELECT * FROM TABLE(VALIDATE(TPCH.ORDERS));
--SELECT * FROM TABLE(VALIDATE(DEMO.FILE_INGESTION_DEMO.EMPLOYEE, JOB_ID => '_last'));
